### ISSUE TITLE
Gamification!

### ISSUE THREAD

**Issue by dpc** [crev-dev/cargo-crev#174]
Why do people do tedious work for free on stackoverflow? Because they get points. Why do they post on reddit? Because they get points.

Add some gamification to `crev` for people to get fame, proof of recognition and acomplishment.

* `cargo crev leaderboard trusted` - sort ids by number of people trusting their review
* `cargo crev leaderboard review` - sort ids by reviewers they have

Some form of easily printing your own stats would be great too.

**Comment by BatmanAoD** [comment]
This would also help with discovery. I don't know anything about Jon Skeet except that he really knows his C#, and I think I'd trust him if he said a particular C# project was well written.

**Comment by dpc** [comment]
There's already an `mvp` command that gives people points. 

It counts number of dependencies for the current project reviewed by given people.

```
~/l/c/cargo-crev (master)> cargo crev crate mvp --trust none
 26 FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE https://github.com/dpc/crev-proofs
 19 X98FCpyv5I7z-xv4u-xMWLsFgb_Y0cG7p5xNFHSjbLA https://github.com/kornelski/crev-proofs
 17 6OZqHXqyUAF57grEY7IVMjRljdd9dgDxiNtr1NF1BdY https://github.com/MaulingMonkey/crev-proofs
 12 lr2ldir9XdBsKQkW3YGpRIO2pxhtSucdzf3M5ivfv4A https://git.sr.ht/~icefox/crev-proofs
 11 Qf4cHJBEoho61fd5zoeweyrFCIZ7Pb5X5ggc5iw4B50 https://github.com/kornelski/crev-proofs
  9 ZOm7om6WZyEf3SBmDC69BXs8sc1VPniYx7Nfz2Du6hM https://gitlab.com/KonradBorowski/crev-proofs
  6 VylyTuk8CMGqIxgHixWaqfiUn3xZyzOA1wFrQ0sR1As https://github.com/BurntSushi/crev-proofs
  3 ZGgmIacywCRKLa33k7W04VFcK-glDkcBXKG4oF7t--4 https://github.com/kpcyrd/crev-proofs
  2 ZCBwWlOeJyU79adJqX9-irGH5wrmuYxUPXeSrFKuayg https://github.com/Lokathor/crev-proofs
  1 aD4K0g6AcSKUDp3VPF7u4hM94zEkqjWeRQwmabLBcV0 https://github.com/Mark-Simulacrum/crev-proofs
  1 YWfa4SGgcW87fIT88uCkkrsRgIbWiGOOYmBbA1AtnKA https://github.com/oherrala/crev-proofs
  1 FBkykBV6YaqAaGoUXyvd-XkEqDYxQNM7EUnZ2nuy-XQ https://github.com/Canop/crev-proofs
  1 gV7ZijKKhdQEbiev0zMLRQKUtUa4zqiTFfLsdREUmSc https://github.com/ryanisaacg/crev-proofs
  1 pt_he2sLPg2w2u4YN7lj-6Gvu25R8aN6ZCcuQFzxC1g https://gitlab.com/phgsng/crev-proofs
```

**Comment by ffranr** [comment]
@dpc, I think this issue should be closed for now. These are my reasons why:

1. Gamification shouldn't be a factor addressed hurriedly. It seems to me like it should be a late stage feature once crev is more mature. This is because what we're encouraging a user to optimize for is subtle. We don't necessarily want to encourage them to review many things. Rather, that their reviews are high value. A high value review, for instance, might be one that is early in making an observation that the general user base comes round to later. Optimizing for review count, on the other hand, might be done hurriedly and provide a false sense of confidence.

2. As you've mentioned above, the `mvp` command already exists and is a significant step towards addressing this issue.

3. This issue has been open for over a year. It doesn't seem important at this stage as it doesn't help in clarifying the scope and purpose of crev. Two factors which must be crystal clear before mass adoption.

**Comment by dpc** [comment]
Agreed.
