### ISSUE TITLE
Improve the rendering of the deps table

### ISSUE THREAD

**Issue by Canop** [crev-dev/cargo-crev#192]
The terminal display of `cargo crev verify deps` exhibits several problems:

* you don't see the header because it scrolled away
* it's very hard to guess what column is what
* breaks when some crates have a long name
* you have no idea of the progress

I think we could

* render on an alternate terminal during the computation so that we can always keep the headers and progress on screen
* use a self adaptive table, with column's width computed from their content and intra-cell wrapping when there's no room
* dump the whole table and warnings on the normal terminal at end of computation

Of course some work would be needed, but also some discussion on the goal.
I prepared a demonstration of the basic idea:

https://dystroy.org/pub/crev-termimad-02.gif

*Let's be clear: I have no PR to propose at the moment, I'd rather discuss it before doing the rest of the work. If you really want to test it here's my fork: https://github.com/Canop/crev/ *

A natural extension on that would be a terminal explorer allowing you to see the dep verification state, with fuzzy searching. This seems rather easy.

**Comment by dpc** [comment]
This is awesome. Please PR, and lets merge.

One thing to take care of is skipping the interactive niceness if `cargo crev` is used in a scripts or piped somewhere. The code already uses `isatty` to detect this.

About the looks - is there any way to actually not use box-like borders? While the interactive features are really nice, I'd prefer the output to be more uniform with how the output looks in "plain" mode, so the difference is not surpring. And to make it easier for tools like `cut` and `sort` it's better if no characters are being used in between the content. Just being able to see the header, and automatic column width adjustment is a huge win.

**Comment by dpc** [comment]
Hmm... now that I think about...

First of all... the way I'm currently processing this list is really lame. It's all serialized, and with a bit of parallelization it could be way faster... eliminating a bit the need for this interactive display. While in progress it should be too fast to actually see anything there.

The width  of columns could be precalculated from the beginning. At least all the crate names and versions are known from the start, so there's no need to adjust them as they go... again, making the interactive redrawing a bit less necessary.

However! I think this whole interactive display maybe should be it's own mode/command, and extended to be even more powerful. Eg. `cargo crev interactive` or something. Maybe even `cargo crev` without arguments should drop users into interactive mode. And then it could support arrows, and changing sorting order, and pressing enter would display more information, and allowing reviewing code from there and so on...

So... I currently think... How about we scale back changed in the normal output: just fix column width and reordering columns like you did. I was planing to do that eventually anyway, and refactor this code to make each command a separate method, on some `struct` etc. so that every piece of that code. If you feel like it, you could parallelize the whole thing if you want.  

And then lets make this interactive output it's own subcomand. We can start with `cargo crev interactive` and when it gets ready, the main `cargo crev`.

**Comment by Canop** [comment]
> And then lets make this interactive output it's own subcomand. We can start with cargo crev interactive and when it gets ready, the main cargo crev.

This is a sensible plan. I think our visions are quite similar.

The way I see it, the same terminal application, the same screen, should be used to display the verification processing (which does need to be parallelized) and to look at verifications when they're done (which means the command wouldn't always recompute everything at launch). A terminal app would make it easy to search, focus on either the problems or the targets for easy reviews, with relevant commands. With this screen you would also be able to launch the various other operations like starting a review or commiting it.

The change I prototyped was just a first step and it could easily be adapted to parallel download for a first and quite easy improvement over the current state. If you think the improvement isn't worth the pain we could forget this step.

*We should probably discuss all this deeper in the chat, starting by the needed refactor.*

**Comment by pickfire** [comment]
`cargo crev verify` does not work well with terminal under 80 columns. Output:
```
status reviews     downloads    own. issues lines  geiger flgs crate
    version         latest_t
none    1  1   122532    179819 0/1    0/0    799      40      half
    1.3.0
none    0  0   773365   2901698 0/3    0/0   1338     498      linked-hash-map
    0.5.2
none    0  0    99132    525923 0/1    0/0   3299       0      serde_cbor
    0.9.0
none    0  0  1733578   3338287 1/1    0/0   2466      55 CB   ryu
    0.2.7
none    0  0  1034736   5774007 1/2    0/0   5298       0      toml
    0.4.10
none    1  2   993742   8543280 1/1    0/0   2337     225      byteorder
    1.2.7
none    0  0  2564936   7430927 1/1    0/0    353       1      itoa
    0.4.3
none    0  0   608805   8121134 1/3    0/0   8842       5      serde_json
    1.0.33
none    0  0    65383  11832105 1/3    0/0   9422       0 CB   serde
    1.0.81
none    0  0    31331    122092 1/1    0/0    355       0      serde-transcode
    1.0.0
none    0  1   626197   2352177 1/2    0/0   4114       0      yaml-rust
    0.4.3
none    0  0  1312566   4994990 1/1    0/0    541       2      dtoa
    0.4.3
```
Maybe there is a better way to reduce the heading size, or instead move them to `--help` or man pages?

**Comment by Canop** [comment]
@pickfire We're working on this problem. I'm working on a screen with columns adapted for the size of the terminal (see similar work: https://github.com/Canop/termimad)

**Comment by BatmanAoD** [comment]
One issue that's not listed here: if `crev` performs downloads, they appear *after* the column headers but *before* the output data:

```
status reviews     downloads    own. issues lines  geiger flgs crate                version         latest_t
  Downloaded parking_lot v0.6.4
  Downloaded ole32-sys v0.2.0
  Downloaded parking_lot_core v0.3.1
  ...
  Downloaded 69 crates (4.3 MB) in 4.53s (largest was `winapi` at 1.1 MB)
none    0  0    54386    249248 1 2   0/0     354       5      futures-io-preview   0.3.0-alpha.18
none    0  0   473108   6201339 3 6   0/0     419       0      unicode-width        0.1.6
...
```

Should I open a separate issue for that?

**Comment by dpc** [comment]
Sure.
