### ISSUE TITLE
`cargo crev trust` to accept an url

### ISSUE THREAD

**Issue by dpc** [crev-dev/cargo-crev#211]
Relevant discussions in #203 . CrevIDs are kind of gnarly and inconvenient. We should strive to hide them from users that are not consciously going to be confirming them off-band.

We can start by making `cargo crev trust` accept an url. In such a case it should:

* fetch that url
* find all IDs that use the same URL as this repo's URL
* create a trust proof for all these URL

This is basically a TOFU.

There should still be a way to accept the raw crevid. Maybe `--id`? Or just autodetect that the argument is not an url, but a CrevID? Or have two commands. `trust url` and `trust id`. I kind of like two commands as it's consistent with other commands i.e. `query id, `fetch url` etc.

**Comment by kornelski** [comment]
`cargo crev trust <whatever>` and having it figure it out would be most usable.

One thing though: it needs to distinguish between a repo of one person's own reviews vs a repo that is an aggregator of everything under the sun.

The risk I see here if there's e.g. `crev.lib.rs/all-the-proofs.git` and someone runs `cargo crev trust crev.lib.rs/all-the-proofs.git` and ends up trusting 1000 people by accident.

OTOH, as mentioned in #203, I've already created 2 identities, and might end up with a few more. So I'd like `cargo crev trust github.com/kornelski` to trust all my IDs.

Solutions I see:

* self-url: have reviews, or some metadata file, contain URL of the repo that was in use when this was published. If self-url == URL to trust, then this is the identity to trust. If different, then assume it's been copied/aggregated, and it's someone elses. Tricky with renames, and repos using different urls for push and pull.

* hardcoded sensible limit: if repo has < 10 identities, assume personal. Otherwise assume aggregate.

* metadata file with a flag to say explicitly. It depends on aggregators toggling it on (or individuals toggling off).

**Comment by dpc** [comment]
@kornelski How about some `.toml` file in root dir of proof repository that just lists own identities?

Also - if you have multiple IDs, would one of them be a "root ID", which trusts all other ones? Maybe instead of a list, we just need metadata with one, single ID that is supported to be used when someone does `cargo crev trust <url>`?

**Comment by kornelski** [comment]
Yeah, file that lists own identities (or identities to trust when you trust this repo) should work.

I have multiple IDs, because I have "work" and "home" computers, and I avoid transferring files between them. Signing keys with other keys sounds too much like PGP.

**Comment by dpc** [comment]
> I have multiple IDs, because I have "work" and "home" computers, and I avoid transferring files between them. Signing keys with other keys sounds too much like PGP.

But  that's what we're talking about -  `crev` does come with a WoT, and `crev trust` does exactly that. Unlike PGP, there are no sub-identities, sub-keys, etc. but different IDs can and are intended to trust each other in some meaningful way.

So if you have two IDs, why would your personal profile not trust the work one? If you don't want to trust your own iDs, why would you use `cargo crev trust` anyway?

I thought about the same setup, and for me, I'd make an ID per-every employer and have `level: high` trust from my core personal ID to them with a potential comment "this is me, just @ myemployer`. Dependening on the company policy I might do the reverse as well, potentially with a lower `level` (because it's crossing the organization boundary).

**Comment by kornelski** [comment]
> why would your personal profile not trust the work one?

I don't have any technical objection to this. 

I just don't like doing key management, and I trust github identities more than crev IDs, so I have very little motivation to manage crev IDs. I don't know what my work and home identities look like. `cargo-crev` has too many commands with too many subcommands, so I would have to figure out how to learn which IDs are mine, and how to properly sign them and how to publish the signatures.

**Comment by dpc** [comment]
> cargo-crev has too many commands with too many subcommands,



You seem go against how `crev` is intended  to be used almost every single time. 

If you don't want to manage Ids... just use one, and use `cargo crev export id` -> `cargo crev import id`.

It's really hard to have software that is minimal, yet satisfying everyones opinion about how they want it to work (flexible), and what they need to achieve (featureful). :D

> I would have to figure out how to learn which IDs are mine, and how to properly sign them and how to publish the signatures.


```
cargo crev query id own
...
cargo crev trust <my_other_id>
```

`cargo-crev` is using `clap` with all the features and discoverability it provides.  `cargo crev help` should give a full overview of available commands.

**Comment by kornelski** [comment]
I appreciate it's difficult to make software, especially easy + secure at the same time.

> You seem go against how crev is intended to be used almost every single time.

Well, cargo-crev without WoT does everything I want from it.

**Comment by kornelski** [comment]
With URL<=>Id mapping verification from #299 this can be implemented now. The interface could be:

```bash
cargo crev trust <URL or Id>
```

If the argument looks like a URL, then crev can fetch it, and trust Ids that have been verified to belong to that repo.

If the argument looks like an Id, then it'd behave like `cargo crev id trust`.
