### ISSUE TITLE
cargo crev verify outputs too many crates

### ISSUE THREAD

**Issue by BurntSushi** [crev-dev/cargo-crev#228]
In a checkout of https://github.com/rust-lang/regex, running `cargo crev verify` shows a line of output for every single dependency in the workspace. Ideally, I'd like to be able to customize this output so that I can narrow my focus. For example, the trust status of all dependencies of `regex` proper is far more important than, say, the trust status of dependencies of my benchmarking harness, or even of all dev-dependencies. I'd like to be able to run a command that shows what's important to me, and my trust level of, say, `libpcre-sys` in this context, is just not important.

I looked at the output of `cargo crev verify --help`, but I don't see any obvious options that will help me do what I want. Most of the options appear dedicated to managing the trust output itself. But I want to actually limit which crates I'm looking at.

This is a problem for a number of my crates that share a workspace with a `criterion`-based benchmark harness. This basically makes the output of `cargo crev verify` mostly noise.

**Comment by dpc** [comment]
Understood. This is definitely not well supported yet. A best workaround that I could suggest is just `|grep -v ignore1|ignore2|...`.

**Comment by BurntSushi** [comment]
Aye. This works for now:

```
$ cargo crev verify | rg -Ff <(cargo tree --no-dev-dependencies --no-indent | cut -d' ' -f1)
```

**Comment by dpc** [comment]
@BurntSushi : I'm sure you'll be delighted to know that some progress was made recently in this regards on `master` branch.

> he trust status of all dependencies of regex proper is far more important than, say, the trust status of dependencies of my benchmarking harness

`cargo crev verify --no-dev-dependencies` is now supported. Along with `--no-default-features` and `--all-featues` working just like in `cargo`.

>  I'd like to be able to run a command that shows what's important to me,


`cargo crev crate verify rand 0.7.0` will display only `rand:0.7.0` and its dependencies. This is to help narrow the view, and also discover the graph better.

BTW. `--recursive` is also implemented, so you can get the recursive metrics we've talked about in the past.

I'm closing, since I don't have plans to add more features in this area right now, but feel free to comment/request more/reopen.
