### ISSUE TITLE
try running editor (from update-alternatives) before vi

### ISSUE THREAD

**Issue by programmerjake** [crev-dev/cargo-crev#232]
I had configured `nano` as the default editor on my system by using update-alternatives.

cargo crev ends up using `vi` as the default editor since I didn't set the `EDITOR` env var or git's `core.editor` value (git ends up using nano without those being set).

crev should try using `editor` (`/usr/bin/editor`) before defaulting to `vi`.

Version:
cargo-crev-crev 0.8.3 installed using cargo install from crates.io

I'm on Ubuntu 18.04 x86_64

**Comment by dpc** [comment]
I looked into how git does things here... 

https://github.com/git/git/blob/6d5b26420848ec3bc7eae46a7ffa54f20276249d/editor.c#L8

and `vi` seems to be a fallback default.

It seems that it is being patched in debian/ubuntu package, here http://archive.ubuntu.com/ubuntu/pool/main/g/git/git_2.7.4-0ubuntu1.6.debian.tar.xz

```
rules
19:  DEFAULT_PAGER=pager DEFAULT_EDITOR=editor \
```

Since `edtior` binary doesn't seem to be any sort of Unix standard... so I'm a bit meh about implementing it. Once `cargo-crev` is package in debian... LOL... they will just have to patch it there too. :D

**Comment by programmerjake** [comment]
would you accept pull requests as long as falling back to vi works when editor is not found?

**Comment by dpc** [comment]
No, because there is no guarantee that `editor` even have to be a text editor on other systems etc. while `vi` considered (informally?) a always-present, default text editor in Unix. And it is just silly, when all it takes... is to set a default global `EDITOR`. :D

**Comment by programmerjake** [comment]
What about if it checks for Debian-based distros where editor is known to be correct before trying editor?  can be checked relatively easily by checking for `/etc/debian_version`
