### ISSUE TITLE
Possible bug in setting up local git repo for a new id

### ISSUE THREAD

**Issue by MonkeysAreEvil** [crev-dev/cargo-crev#277]
So I just started playing with cargo-crev today and just ran into two weird issues, possibly related. I've been following the getting started doc, and reviewed one of my small libs.

On running `cargo crev repo publish` I got a `Repository not found` error. Turns out that running `cargo crev id new --url https://git.sr.ht/~happy_shredder/crev-proofs`
actually set the origin url to /crev-proofs.git, which is incorrect.

On fixing that, I then ran `cargo crev repo publish` I then got `First, rewinding head to replay your work on top of it...` which wiped out the the commit from `crev id trust`, and the commit from the review.

On refetching dpc/crev-proofs, retrusting, and rereviewing I can publish successfully.

So something weird happened in the initial id creation. Not quite sure what though.

---
System details:
cargo-crev 0.14.0
cargo install cargo-crev
Funtoo 1.4, Linux 5.2.7, git 2.24.1

**Comment by dpc** [comment]
Please excuse all the troubles. There's only so many hours in a day, so the rarely used paths might have rough edges.


The first one might have been: https://github.com/crev-dev/cargo-crev/blob/e329cbc3fd9f57a420ab4dcc9d571a7a65b44529/crev-lib/src/util/git.rs#L26

In here: https://github.com/crev-dev/cargo-crev/blob/e329cbc3fd9f57a420ab4dcc9d571a7a65b44529/crev-lib/src/util/git.rs#L85 we're trying to convert `https` url to `git` url, and I think what we're doing matches `github` and `gitlab`, but not `sr.ht`. If you'd like to help, please submit a PR that ... hmmm...  does the `.git` prefix only on `github` and `gitlab` case? 



Because of that problem https://github.com/crev-dev/cargo-crev/blob/b51d8182b169aaa36ab98af136620120342b8ca8/crev-lib/src/local.rs#L435 failed, and something was not set right in local repository. If `clone` fails, we should probably display the same message that https://github.com/crev-dev/cargo-crev/blob/b51d8182b169aaa36ab98af136620120342b8ca8/crev-lib/src/local.rs#L414 shows.

But the question is - is the recommended command even working correctly?

**Comment by MonkeysAreEvil** [comment]
No worries. Yeah it was easy enough to recover just a little bump in setting up :)

I can definitely do a PR that fixes the `.git` prefix, maybe later today? I'll see how I go for time. Although, I feel like there's something a bit fragile about branching for github, sr.ht and whatever else might show up. Maybe there's a more robust way to convert from https to git?

I can have a look at local.rs as well. I'll have to check how exactly `clone` failed, to figure out what to report to the user.

**Comment by dpc** [comment]
> Maybe there's a more robust way to convert from https to git?

Any hosting service is free to expose http and git endpoints under any path they desire. They could be even visible under different hostnames etc.

**Comment by MonkeysAreEvil** [comment]
> They could be even visible under different hostnames etc
Yeah I've been thinking about this the last couple of days, I think you're right. I'll try and do a PR within the next couple of days.

**Comment by dpc** [comment]
This should be somewhat improved now.
