### ISSUE TITLE
crev should track repo URLs proofs were fetched from

### ISSUE THREAD

**Issue by kornelski** [crev-dev/cargo-crev#298]
I'm [writing a GUI](https://mastodon.social/@kornel/103946700810036107) and I would like to have a feature to add trusted users by their GitHub usernames or URLs.

In order to do this securely, I have to establish which Crev Ids legitimately belong to a URL, but crev-lib doesn't seem to have an API for that.

It has a repo URL from body of the proof, but there's no guarantee that this value is true.

In a proof:

```yaml
from:
  id-type: crev
  id: XXYZXYX
  url: "https://github.com/$USER/crev-proofs"
```

Only the `id` can be trusted (if signature matches). The `url` can't, because anyone can put any value they like (e.g. anyone can run `cargo crev id new --github-username dpc`).

So identities require a two-way check. I need to check that the repo at a given URL contains its own URL, and then I can know that the Id that signed this owns this repo (or the repo owner has been foolish enough to publish someone else's spoofed proof…)

**Comment by dpc** [comment]
> (or the repo owner has been foolish enough to publish someone else's spoofed proof…)

I'm not really sure if I understand. Generally, repositories are just dumb stores of proof. Proofs don't have to be of the owner of the repo. In the future, we might have repositories that aggregate proofs from multiple people, etc.

So the `url` was envisioned as a advise "if you ever want more proofs from me, try this url". I was hoping that in the future more "transport meachnisms" etc. will be added, and one will be able to download proofs from websites, bittorrent, ipfs or whatever else.

At least that was the vision. This way there's even absolutely no trust placed on github or whatever else git repo host etc.

I realize that this complicates the UX, because many users expect "oh, I just have that github usenrame and that identifies the user, and just figure out the ID" etc.

**Comment by dpc** [comment]
On the other hand some other users complain "git repos are untrustworthy and it's really bad that people will be only paying attention to github url, which is a possible attack vector".

This is generally the problem with online webs of trust, and the reason why PGP users have these signing parties etc. where they check their passports, etc. :man_shrugging: 

I generally think that the best compromise: if the user used just the url, fetch the repo, read all the proofs from it, and if there was only one ID signing everything - take that as the ID, if there were more - give user the choice to pick one they want to use.

**Comment by kornelski** [comment]
Currently crev has a weakness that a mere fetch of a repo is already putting trust in it. Currently crev trusts that all Id->URL mappings in all `from:` are valid and uses them as if they were real. It will display them next to identities in `id query all`.

If user fetches any repo they don't trust:

* the repo can pretend to be anyone else's crev Id by copying their proofs
* the repo can associate a false URL with *someone else's* Id

So this change doesn't put more trust in GitHub, it removes the accidental trust that already exists.

With #299

* for any fetched repo it's clear which identities are repo's own, and which are copies from other known Ids that never claimed to use that repo (this isn't treated as error, only FYI for the user)
* crev knows when a repo talks about other people's URLs, and can display this accordingly (e.g. `id query all` can't be spoofed).

**Comment by dpc** [comment]
> Currently crev trusts that all Id->URL mappings in all from: are valid and uses them as if they were real. It will display them next to identities in id query all.

We only trust that it's in the best interest of the user to correctly self-report best known url to fetch updates from. From the perspective of the rest of the crev, it doesn't really matter if it's true. I think you might not acknowledge that because you'd like to rely on the opposite.

> the repo can associate a false URL with someone else's Id via the secondary fallback.

Yes. The fallback urls only works this way: when looking for an url to fetch updates from, use urls reported by other users, if you don't have the url reported and signed by the Id itself. As long as you don't use the fact that you fetched an url as a certain proof that IDs in it are somehow special, the only thing you risk is downloading bunch of garbage and wasting space on disk (which is another problem that is not currently addressed).


>  It's technically a user error to trust based on a URL displayed by the tool, but such gotcha is unfair to users.

I agree with that being somewhat of a problem, but it doesn't invalidate the fact that the IDs are a primary subject of trust, and URLs are only a "if you are looking for more proofs from me use this URL" kind of thing.

The reverse mapping "url -> id" will never be bullet-proof, and it will be a security hole if users rely only on them. I don't think there's a way around it.

**Comment by dpc** [comment]
Right now as the code is what was downloaded from where did not matter because nothing is special. It doesn't matter where each stuff was downloaded from. The stuff that is used for any decisions is cryptographically signed anyway.

I think it is worthwhile making the `_secondary` fallback smarter (eg. only using URLs reported by another trusted user).

When user does `cargo crev fetch <id>` we could look up the matching url by:

* looking for self-reported url
* looking for url reported by another trusted user
* looking for url reported by any user **and warning user that they need to check it**
* telling user that we don't have an url right now

When user does `cargo crev trust <url>`, we can:

* build a reverse mapping  or "url -> id" from proofs reported by existing trusted users, or
* fetch the url, display available IDs, possibly pre-select one that looks like the one by the user and  **and warn user that they must check if these ids really belong to the user they expected under given url**

**Comment by dpc** [comment]
> for any fetched repo it's clear which identities are repo's own,

So the insight here is that proofs with `from.url` the same as the downloaded repo, is a strong indication that the ID belongs to the owner of the repo.

I like that and I think it makes "possibly pre-select one that looks like the one by the user" quite reliable.

However security wise it is not an improvement. The repo could be compromised / connection MitMed, and returned proofs are signed by a malicious ID, and `from.url` set to the same url, to fool the downloading user.
