### ISSUE TITLE
Light reviews for platform-specific crates?

### ISSUE THREAD

**Issue by Kixunil** [crev-dev/cargo-crev#379]
I wrote a program that's intended to run on Linux only, primarily `x86_64` and secondarily on `arm64`. At least for now. When running `cargo crev verify` I get a list of various platform-dependent crates such as `winapi-x86_64-pc-windows-gnu` or `wasi` I don't care about (transitive dependencies).

I'd like to decrease the amount of work needed to verify dependencies by seeing that someone (number/list of reviewers) verified that platform-specific crate is correct or empty on unsupported platforms (the same person might have or might have not reviewed the code for other platforms - I don't care). Further, if I am the one who verifies it, I'd like to publish a proof in such way that *does not confuse* others into thinking I have verified whole code.

A cursory search doesn't show up any indication of this being supported already in any way. Would it be possible to add support for such feature?

**Comment by dpc** [comment]
IIRC, we already support features in `crate verify` so that would skip some platform-specific crates from the verification. Just mentioning it since its related.


I'm not sure how exactly would this work, since it seems to have ... bad defaults. Hmm... Maybe it should be negative? One would list parts that were not reviewed? 

```
unreviewed-parts: # structure and names to be bikeshed
  platform:
  - arm
```

Clients unaware of this, would simply ignore that key and assume everything was reviewed, just like in the past. Client that would handle this additional data, would either display some notes, or the user could ignore reviews that list ignoring parts that they do care about it.

**Comment by dpc** [comment]
Having said that it is getting somewhat complicated from the UX perspective and I'm not sure if it's very worthwile already. Details like this can already be listed in the comment section.

**Comment by Kixunil** [comment]
Why do you think the defaults are bad? I believe misleading someone to think a piece of code was reviewed is worse than making someone think the code was not reviewed.

I imagine `crev` having a config file with `target_platforms` containing a list of canonical identifiers. Then a review would contain `review-whitelist` key with the list of reviewed platforms. `cargo crev verify` would then use the configuration to display these special reviews only when they specify targeted platforms.

Good point about old versions though. Ideally they should ignore the whole review if they don't understand these fields but I'm not sure it's possible. If not, maybe it's a good reason to add a way to do this ASAP.

**Comment by dpc** [comment]
The concept of a platform is very Rust-specific. Some language don't have platform-specific code at all. And the whole part generalizes easily: someone might not be able to review cryptographic parts of a project so they want to mention that.

So listing things that one *did review* "defaults incorrectly" in part because it doesn't tell the reader which are the parts that were not reviewed.

If we revert this proposition: then it's job of the reviewer to list the parts that were not reviewed, then the reader can assume everything rest was reviewed. Which shifts identifying and defining parts to someone that actually did the reviewing and can tell this and that about what part are there.

Fundamentally by "default correctly" I mean, that the current way reviews are done must match this extension. "Lack of any additional info" must match "everything is assumed to be reviewed." So listing parts that were not reviewed defaults more correctly.

**Comment by Kixunil** [comment]
Ah, so I think there are two misunderstandings, so my clarifications:

* I believe the default should be to **not** display a partial review in **summary outputs**. Displaying them in extended outputs where the user can see they are not full is fine. Actually, I prefer to display it in extended outputs.
* No explicit information should mean "everything reviewed". Only when the appropriate key (`review-whitelist`) is present treat it as a whitelist.

> someone might not be able to review cryptographic parts of a project so they want to mention that.

This is an interesting scenario that could perhaps reuse the same concepts and it's worth to think about a bit. I'm now mostly concerned with platform-dependent stuff which I believe should have consistent naming across all projects to be useful.

**Comment by dpc** [comment]
> I believe the default should be to not display a partial review in summary outputs. Displaying them in extended outputs where the user can see they are not full is fine. Actually, I prefer to display it in extended outputs.

This does not address the fact that crev aims at being a ... let's say ... extensible convention-based standard.Which should support multiple languages etc. And clients should handle well extensions they don't understand. Which means that some clients of it might never implement and understand that there's a magic key for platform-related things, etc. So they will treat both documents without this new list and with it (since they don't understand) as "full review".

So, IMO, it's better to treat that list as a "additive" information that just clarifies the scope of the review, by specifying things that were not covered. crev already does not require full or extensive review, under the assumption that "it's better to know that you glanced over something, than not know about any pair of eyes" and relying on redundancy of independent reviews, instead of trying to get a single perfect review.

> This is an interesting scenario that could perhaps reuse the same concepts and it's worth to think about a bit

I really want to avoid the crev proof format to be a long list of narrow features, and instead prefer small set of general purpose mechanisms.

**Comment by Kixunil** [comment]
Would it make sense to add a small requirement for all implementations to understand some kind of "incomplete" flag and display some marker (e.g. exclamation mark) around such reviews in summaries? No requirement to do anything else. It'd simply mean "check the description before relying on this review".

Knowing that some reviews are actually quick looks doesn't give me much confidence in `crev`. :(

**Comment by dpc** [comment]
> Knowing that some reviews are actually quick looks doesn't give me much confidence in crev. :(

That's what self-reported `thoroughness` and `understanding` fields are for, along with options passed to `cargo crev verify` to filter out any reviews that don't meet your requirements. 

"Quick looks" are better than nothing, and there aren't even enough of "quick looks" to make the whole thing widely viable, so worrying about how to coordinate hypothetical extensive and details reports seem premature.

I'm closing because I don't think this is worth spending time on right now, but it could be a reasonable extension in the future.

**Comment by Kixunil** [comment]
Sure, I have a use case for it (wanting to do Linux-only software AND having it reviewed) but if I'm the only one, then it doesn't matter.
